title: Habeeb Hassan # your name (or website title) here
logo: "/images/WhatsApp Image 2020-04-05 at 1.01.24 PM.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I currently work as a software engineer at Reviewbox where I focus on full stack web development, data engineering, and NLP analysis. I attended Michigan Technological University where I recieved a B.S. in Physics. While pursuing my degree, I was also passionate about cycling and after graduating, I had the opportunity to race professionally.
  <br><br>
In total, I spent 5 years racing as a professional cyclist. I was on a 6 rider roster that won the 2015 US Team Time Trial National Championship, which also allowed me to compete at the 2015 World Championships. I've been on the podium at national level races, and I've had the opportunity to race against some of the best cyclists in the world. Through cycling, I was able to develop a strong work ethic, teamwork, and a unique perpective of the world. It was an incredible experience.  <br><br>
  <a href="https://www.linkedin.com/in/habeebhassan-08/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
